name = "BSS Stocktake"
client_id = "59081b6dfc7d274561f3311d434cbe43"
application_url = "https://stocktake-a5sq.onrender.com"
embedded = true

[access_scopes]
scopes = "read_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "https://stocktake-a5sq.onrender.com/auth/callback"
]

[webhooks]
api_version = "2026-07"

[pos]
embedded = false
